services:
  seafile:
    image: seafileltd/seafile-pro-mc:13.0-latest
    container_name: seafile-dev
    ports:
      - "8080:80"
    volumes:
      - seafile-data:/shared
    environment:
      - INIT_SEAFILE_MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - SEAFILE_MYSQL_DB_HOST=mariadb
      - SEAFILE_MYSQL_DB_PORT=3306
      - SEAFILE_MYSQL_DB_USER=root
      - SEAFILE_MYSQL_DB_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - SEAFILE_MYSQL_DB_CCNET_DB_NAME=ccnet_db
      - SEAFILE_MYSQL_DB_SEAFILE_DB_NAME=seafile_db
      - SEAFILE_MYSQL_DB_SEAHUB_DB_NAME=seahub_db
      - INIT_SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - INIT_SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_HOSTNAME=127.0.0.1
      - SEAFILE_SERVER_PROTOCOL=http
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - SEAFILE_LOG_TO_STDOUT=true
      - TIME_ZONE=Europe/Berlin
      - CACHE_PROVIDER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ENABLE_SEADOC=false
      - ENABLE_NOTIFICATION_SERVER=false
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - seafile-net

  mariadb:
    image: mariadb:11.4.3-noble
    container_name: mariadb-dev
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - seafile-net

  redis:
    image: redis:7.2.7-bookworm
    container_name: redis-dev
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - seafile-net

volumes:
  seafile-data:
  mariadb-data:
  redis-data:

networks:
  seafile-net:
